# SPDX-License-Identifier: Apache-2.0
# The CLI emits UTF-8 bytes. Specify decoding so Windows OEM code pages cannot
# corrupt valid non-ASCII output before CMake's JSON parser sees it.
execute_process(COMMAND "${CLI}" discover --json RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors ENCODING UTF-8)
if(NOT status EQUAL 0 OR NOT errors STREQUAL "")
  message(FATAL_ERROR "CLI fixture failed: ${status} ${errors}")
endif()
string(JSON schema GET "${output}" schema_version)
string(JSON features GET "${output}" devices 0 services 0 features)
string(JSON password GET "${output}" devices 0 services 0 password_required)
string(JSON flag TYPE "${output}" devices 0 services 0 txt flag)
string(JSON empty GET "${output}" devices 0 services 0 txt empty)
string(JSON binary GET "${output}" devices 0 services 0 txt_value_hex binary)
string(JSON compatibility GET "${output}" compatibility_validated)
string(JSON name GET "${output}" devices 0 name)
string(JSON utf8 GET "${output}" devices 0 services 0 txt utf8)
string(HEX "${utf8}" utf8_hex)
string(JSON invalid_utf8_hex GET "${output}" devices 0 services 0 txt_value_hex invalid_utf8)
if(NOT schema EQUAL 1 OR NOT features STREQUAL "0xffffffffffffffff" OR password
   OR NOT flag STREQUAL "NULL" OR NOT empty STREQUAL "" OR NOT binary STREQUAL "00ff" OR compatibility)
  message(FATAL_ERROR "Incorrect JSON field semantics: ${output}")
endif()
if(NOT utf8_hex STREQUAL "c3a9" OR NOT invalid_utf8_hex STREQUAL "c080eda080f4908080c2")
  message(FATAL_ERROR "UTF-8 display or exact binary TXT preservation failed")
endif()
string(ASCII 27 escape)
set(expected_name "TV\"\\\n${escape}")
if(NOT name STREQUAL expected_name)
  message(FATAL_ERROR "JSON control/name round trip failed")
endif()
execute_process(COMMAND "${CLI}" discover RESULT_VARIABLE status OUTPUT_VARIABLE readable ENCODING UTF-8)
string(FIND "${readable}" "\\u001b" escaped_position)
string(FIND "${readable}" "${escape}" raw_position)
if(NOT status EQUAL 0 OR escaped_position EQUAL -1 OR NOT raw_position EQUAL -1)
  message(FATAL_ERROR "Human-readable output leaked terminal controls")
endif()
