# SPDX-License-Identifier: Apache-2.0
execute_process(COMMAND "${CLI}" discover --json RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT errors STREQUAL "")
  message(FATAL_ERROR "CLI fixture failed: ${status} ${errors}")
endif()
string(JSON schema GET "${output}" schema_version)
string(JSON features GET "${output}" devices 0 services 0 features)
string(JSON password GET "${output}" devices 0 services 0 password_required)
string(JSON flag TYPE "${output}" devices 0 services 0 txt flag)
string(JSON empty GET "${output}" devices 0 services 0 txt empty)
string(JSON binary GET "${output}" devices 0 services 0 txt_value_hex binary)
string(JSON compatibility GET "${output}" compatibility_validated)
string(JSON name GET "${output}" devices 0 name)
if(NOT schema EQUAL 1 OR NOT features STREQUAL "0xffffffffffffffff" OR password
   OR NOT flag STREQUAL "NULL" OR NOT empty STREQUAL "" OR NOT binary STREQUAL "00ff" OR compatibility)
  message(FATAL_ERROR "Incorrect JSON field semantics: ${output}")
endif()
string(ASCII 27 escape)
set(expected_name "TV\"\\\n${escape}")
if(NOT name STREQUAL expected_name)
  message(FATAL_ERROR "JSON control/name round trip failed")
endif()
execute_process(COMMAND "${CLI}" discover RESULT_VARIABLE status OUTPUT_VARIABLE readable)
string(FIND "${readable}" "\\u001b" escaped_position)
string(FIND "${readable}" "${escape}" raw_position)
if(NOT status EQUAL 0 OR escaped_position EQUAL -1 OR NOT raw_position EQUAL -1)
  message(FATAL_ERROR "Human-readable output leaked terminal controls")
endif()
